"""
Hybrid License System with RSA Signature + Online Revocation Check + AES Encryption
====================================================================================

Architecture:
1. **Offline Validation**: RSA-2048 signature verification
2. **Hardware Binding**: License tied to device's hardware ID (MAC + CPU Serial)
3. **Online Revocation**: Periodic check if license was revoked
4. **Trial Period**: 7 days free trial before requiring license
5. **AES Encryption**: License file encrypted with AES-256-GCM
6. **Cython Compiled**: This module is compiled to .pyd/.so to prevent reverse engineering

License Format:
    DEVICE-ID: SHA256(MAC + CPU Serial + Platform)
    LICENSE-KEY: Base64(RSA-Signature(DEVICE-ID + License-ID + Timestamp))
    LICENSE-FILE: AES-256-GCM encrypted JSON
    
Workflow:
    User Install â†’ Generate Device ID â†’ Send to Admin
    Admin Signs â†’ User Activates â†’ App Validates Offline
    Background Check â†’ Server Revocation List â†’ Cache 24h
    
Security Features:
    âœ… RSA-2048 cryptographic signatures (can't forge)
    âœ… Hardware binding (can't transfer to other machines)
    âœ… AES-256-GCM encryption (can't edit license file)
    âœ… Cython compilation (can't read source code)
    âœ… Online revocation (can remotely disable)
"""

import os
import json
import hashlib
import platform
import uuid
import subprocess
import base64
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, Tuple
import threading
import time

# RSA verification (embedded public key)
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.backends import default_backend
from cryptography.exceptions import InvalidSignature

# AES encryption for license file
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# === RSA PUBLIC KEY (Embedded in Application) ===
# This key is used to verify license signatures (offline validation)
# Generated by tools/generate_rsa_keys.py
# REPLACE THIS WITH YOUR ACTUAL PUBLIC KEY AFTER RUNNING generate_rsa_keys.py
PUBLIC_KEY_PEM = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn4Fwz9oOBQzl1+j1JKu5
UJo9KTroUM5pPN8hZspjiubhpl4wTsDacJD1dm1TtQ70YEj2zcTDr7FWMgGK7N4+
fuEobuxyopjguiHngSXy5d3Oj1H6HSbNDp5m8qXOT4lMNJDfUHICNs4zH/6dvge7
QTDTq93ehQb7q9OI20r58hyBNvN1/ZzszdrOPOeBSAsIvo6IxGcKV0E2bRTgIu7l
4n9kfGjISNOzJe9f4s/Jtaeu8zEuO4EoxJDcIBxKeEWj14o/PN2AtX7cyGw9Q+9Z
hdzKH+m/sQYAID9uJ2Jn5PE40DR/xGaoaE9QVMvyhB+xatDM40AF5SPWLHe4+v0F
awIDAQAB
-----END PUBLIC KEY-----
"""

# === CONFIGURATION ===
REVOCATION_SERVER = "http://localhost:5000"  # Change to production URL
REVOCATION_CHECK_INTERVAL = 86400  # 24 hours
TRIAL_DAYS = 7

# AES Encryption Key (derived from hardware ID)
# This ensures license file can only be decrypted on the same machine
AES_SALT = b"DMXMaster_License_Salt_v1.0_DoNotShare"

# File paths
CONFIG_DIR = Path(__file__).parent.parent.parent / "config"
LICENSE_FILE = CONFIG_DIR / "license.lic"  # Changed to .lic (encrypted)
REVOCATION_CACHE_FILE = CONFIG_DIR / "revocation_cache.json"
INSTALL_DATE_FILE = CONFIG_DIR / "install_date.txt"

logger = logging.getLogger(__name__)


class LicenseManager:
    """Manages license activation and validation"""
    
    def __init__(self):
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        self._device_id = self._get_hardware_id()
        self._public_key = self._load_public_key()
        self._aes_key = self._derive_aes_key()
        self._revocation_check_thread = None
        
    def _derive_aes_key(self) -> bytes:
        """
        Derive AES-256 key from hardware ID
        This ensures license file can only be decrypted on the same machine
        """
        # Use PBKDF2 to derive 32-byte key from device ID
        from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
        
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,  # 256 bits
            salt=AES_SALT,
            iterations=100000,
            backend=default_backend()
        )
        aes_key = kdf.derive(self._device_id.encode('utf-8'))
        return aes_key
    
    def _encrypt_license_data(self, license_data: dict) -> bytes:
        """
        Encrypt license data with AES-256-GCM
        Returns: encrypted_data (includes nonce + ciphertext + tag)
        """
        try:
            # Convert to JSON bytes
            json_bytes = json.dumps(license_data).encode('utf-8')
            
            # Create AESGCM instance
            aesgcm = AESGCM(self._aes_key)
            
            # Generate random nonce (12 bytes for GCM)
            nonce = os.urandom(12)
            
            # Encrypt (GCM provides authentication)
            ciphertext = aesgcm.encrypt(nonce, json_bytes, None)
            
            # Combine: nonce + ciphertext (tag is included in ciphertext)
            encrypted_data = nonce + ciphertext
            
            logger.info("License data encrypted with AES-256-GCM")
            return encrypted_data
            
        except Exception as e:
            logger.error(f"License encryption failed: {e}")
            raise
    
    def _decrypt_license_data(self, encrypted_data: bytes) -> dict:
        """
        Decrypt license data with AES-256-GCM
        Raises exception if decryption fails (wrong machine or tampered file)
        """
        try:
            # Extract nonce (first 12 bytes)
            nonce = encrypted_data[:12]
            ciphertext = encrypted_data[12:]
            
            # Create AESGCM instance
            aesgcm = AESGCM(self._aes_key)
            
            # Decrypt and verify authentication tag
            json_bytes = aesgcm.decrypt(nonce, ciphertext, None)
            
            # Parse JSON
            license_data = json.loads(json_bytes.decode('utf-8'))
            
            logger.info("License data decrypted successfully")
            return license_data
            
        except Exception as e:
            logger.error(f"License decryption failed: {e}")
            raise ValueError("License file is corrupted or not for this machine")
        
    def _get_hardware_id(self) -> str:
        """
        Generate unique hardware ID from:
        - MAC Address
        - CPU Serial (Windows: WMIC, Linux: /proc/cpuinfo)
        - Platform info
        
        Returns: SHA-256 hash (64 chars)
        """
        components = []
        
        # Platform info
        components.append(platform.system())
        components.append(platform.node())
        components.append(platform.machine())
        
        # MAC address
        mac = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff)
                       for elements in range(0, 48, 8)][::-1])
        components.append(mac)
        
        # CPU Serial (platform-specific)
        try:
            if platform.system() == 'Windows':
                # Windows: Use WMIC to get CPU ProcessorId
                cmd = 'wmic cpu get ProcessorId'
                output = subprocess.check_output(cmd, shell=True).decode()
                cpu_id = output.split('\n')[1].strip()
                components.append(cpu_id)
            elif platform.system() == 'Linux':
                # Linux/Raspberry Pi: Read from /proc/cpuinfo
                with open('/proc/cpuinfo', 'r') as f:
                    for line in f:
                        if line.startswith('Serial'):
                            serial = line.split(':')[1].strip()
                            components.append(serial)
                            break
        except Exception as e:
            logger.warning(f"Could not get CPU serial: {e}")
            # Fallback to processor name
            components.append(platform.processor())
        
        # Generate SHA-256 hash
        fingerprint = '|'.join(components).encode('utf-8')
        device_id = hashlib.sha256(fingerprint).hexdigest()
        
        logger.info(f"Device ID generated: {device_id[:16]}...")
        return device_id
    
    def _load_public_key(self):
        """Load RSA public key for signature verification"""
        try:
            public_key = serialization.load_pem_public_key(
                PUBLIC_KEY_PEM.encode(),
                backend=default_backend()
            )
            logger.info("RSA public key loaded successfully")
            return public_key
        except Exception as e:
            logger.error(f"Failed to load public key: {e}")
            return None
    
    def get_device_id(self) -> str:
        """Get device ID for user to send to admin"""
        return self._device_id
    
    def get_trial_info(self) -> dict:
        """
        Get trial period information
        
        Returns:
            {
                'is_trial': bool,
                'install_date': datetime,
                'days_remaining': int,
                'is_expired': bool
            }
        """
        if not INSTALL_DATE_FILE.exists():
            # First run - create install date
            install_date = datetime.now()
            INSTALL_DATE_FILE.write_text(install_date.isoformat())
        else:
            install_date = datetime.fromisoformat(INSTALL_DATE_FILE.read_text().strip())
        
        days_since_install = (datetime.now() - install_date).days
        days_remaining = max(0, TRIAL_DAYS - days_since_install)
        
        return {
            'is_trial': True,
            'install_date': install_date,
            'days_remaining': days_remaining,
            'is_expired': days_remaining <= 0
        }
    
    def is_licensed(self) -> bool:
        """Check if software is properly licensed"""
        # Check if license file exists and is valid
        if LICENSE_FILE.exists():
            license_data = self._load_license()
            if license_data and self._validate_license_offline(license_data):
                return True
        
        # Check trial period
        trial_info = self.get_trial_info()
        return not trial_info['is_expired']
    
    def is_valid(self) -> Tuple[bool, str]:
        """
        Check if software is properly licensed (with message)
        Returns: (is_valid: bool, message: str)
        """
        # Check if license file exists and is valid
        if LICENSE_FILE.exists():
            license_data = self._load_license()
            if license_data and self._validate_license_offline(license_data):
                email = license_data.get('customer_email', 'Unknown')
                issued = license_data.get('issued_date', 'Unknown')
                return True, f"Licensed to {email} (issued: {issued})"
        
        # Check trial period
        trial_info = self.get_trial_info()
        if not trial_info['is_expired']:
            days = trial_info['days_remaining']
            return True, f"Trial: {days} days remaining"
        else:
            return False, "Trial expired"
    
    def is_admin(self) -> bool:
        """
        Check if current user has admin license
        Admin license allows: Delete shows, Edit shows, Advanced settings
        Returns: True if licensed (not trial), False if trial mode
        """
        if LICENSE_FILE.exists():
            license_data = self._load_license()
            if license_data and self._validate_license_offline(license_data):
                # Licensed users = Admin
                return True
        
        # Trial users = No admin rights
        return False
    
    def _load_license(self) -> Optional[dict]:
        """
        Load and decrypt license data from encrypted file
        """
        try:
            if not LICENSE_FILE.exists():
                return None
            
            # Read encrypted binary data
            with open(LICENSE_FILE, 'rb') as f:
                encrypted_data = f.read()
            
            # Decrypt (will fail if wrong machine or tampered)
            license_data = self._decrypt_license_data(encrypted_data)
            
            logger.info("License loaded and decrypted successfully")
            return license_data
            
        except ValueError as e:
            # Decryption failed - wrong machine or corrupted file
            logger.error(f"License decryption failed: {e}")
            return None
        except Exception as e:
            logger.error(f"Failed to load license: {e}")
            return None
    
    def _save_license(self, license_data: dict):
        """
        Encrypt and save license data to file
        """
        try:
            # Encrypt license data
            encrypted_data = self._encrypt_license_data(license_data)
            
            # Write binary encrypted data
            with open(LICENSE_FILE, 'wb') as f:
                f.write(encrypted_data)
            
            logger.info("License encrypted and saved successfully")
            
        except Exception as e:
            logger.error(f"Failed to save license: {e}")
            raise
    
    def _validate_license_offline(self, license_data: dict) -> bool:
        """
        Validate license using RSA signature (offline)
        
        License data structure:
        {
            'device_id': 'sha256_hash',
            'signature': 'base64_rsa_signature',
            'issued_date': 'ISO timestamp',
            'license_id': 'unique_uuid',
            'customer_email': 'user@example.com'
        }
        """
        if not self._public_key:
            logger.error("Public key not loaded")
            return False
        
        try:
            # Check device ID match
            if license_data.get('device_id') != self._device_id:
                logger.error("Device ID mismatch")
                return False
            
            # Reconstruct signed message
            message = f"{license_data['device_id']}|{license_data['license_id']}|{license_data['issued_date']}"
            message_bytes = message.encode('utf-8')
            
            # Decode signature
            signature = base64.b64decode(license_data['signature'])
            
            # Verify RSA signature
            self._public_key.verify(
                signature,
                message_bytes,
                padding.PSS(
                    mgf=padding.MGF1(hashes.SHA256()),
                    salt_length=padding.PSS.MAX_LENGTH
                ),
                hashes.SHA256()
            )
            
            logger.info("License signature valid (offline)")
            return True
            
        except InvalidSignature:
            logger.error("Invalid license signature")
            return False
        except Exception as e:
            logger.error(f"License validation error: {e}")
            return False
    
    def activate_license(self, license_key: str) -> Tuple[bool, str]:
        """
        Activate license with provided key
        
        Args:
            license_key: JSON string from admin tool
            
        Returns:
            (success: bool, message: str)
        """
        try:
            # Parse license JSON
            license_data = json.loads(license_key)
            
            # Validate offline
            if not self._validate_license_offline(license_data):
                return False, "Invalid license key or device mismatch"
            
            # Save license
            self._save_license(license_data)
            
            # Start background revocation check
            self._start_revocation_check()
            
            return True, "License activated successfully!"
            
        except json.JSONDecodeError:
            return False, "Invalid license format"
        except Exception as e:
            logger.error(f"Activation failed: {e}")
            return False, f"Activation error: {str(e)}"
    
    def _start_revocation_check(self):
        """Start background thread to check license revocation"""
        if self._revocation_check_thread and self._revocation_check_thread.is_alive():
            return  # Already running
        
        def check_loop():
            while True:
                self._check_revocation_online()
                time.sleep(REVOCATION_CHECK_INTERVAL)
        
        self._revocation_check_thread = threading.Thread(target=check_loop, daemon=True)
        self._revocation_check_thread.start()
        logger.info("Started background revocation check")
    
    def _check_revocation_online(self) -> bool:
        """
        Check if license was revoked (online)
        Returns True if license is still valid
        """
        license_data = self._load_license()
        if not license_data:
            return False
        
        try:
            import urllib.request
            
            # Prepare request
            url = f"{REVOCATION_SERVER}/api/license/check_revoked"
            data = json.dumps({
                'license_id': license_data['license_id'],
                'device_id': self._device_id
            }).encode('utf-8')
            
            req = urllib.request.Request(
                url,
                data=data,
                headers={'Content-Type': 'application/json'},
                method='POST'
            )
            
            # Send request (10 second timeout)
            with urllib.request.urlopen(req, timeout=10) as response:
                result = json.loads(response.read().decode('utf-8'))
                is_valid = result.get('valid', False)
                
                # Cache result
                cache_data = {
                    'is_valid': is_valid,
                    'last_check': datetime.now().isoformat(),
                    'reason': result.get('reason', '')
                }
                
                with open(REVOCATION_CACHE_FILE, 'w') as f:
                    json.dump(cache_data, f)
                
                if not is_valid:
                    logger.warning(f"License revoked: {result.get('reason', 'Unknown')}")
                else:
                    logger.info("License valid (online check)")
                
                return is_valid
                
        except Exception as e:
            logger.warning(f"Online revocation check failed: {e}")
            # Use cached result if available
            if REVOCATION_CACHE_FILE.exists():
                try:
                    with open(REVOCATION_CACHE_FILE, 'r') as f:
                        cache = json.load(f)
                        last_check = datetime.fromisoformat(cache['last_check'])
                        # Cache valid for 24 hours
                        if (datetime.now() - last_check).total_seconds() < 86400:
                            logger.info("Using cached revocation status")
                            return cache.get('is_valid', True)
                except Exception:
                    pass
            
            # If offline and no cache, assume valid
            return True
    
    def get_license_info(self) -> dict:
        """
        Get current license information
        
        Returns:
            {
                'is_licensed': bool,
                'device_id': str,
                'trial_days_remaining': int,
                'license_data': dict or None,
                'last_revocation_check': datetime or None
            }
        """
        license_data = self._load_license()
        trial_info = self.get_trial_info()
        
        # Get last revocation check
        last_check = None
        if REVOCATION_CACHE_FILE.exists():
            try:
                with open(REVOCATION_CACHE_FILE, 'r') as f:
                    cache = json.load(f)
                    last_check = datetime.fromisoformat(cache['last_check'])
            except Exception:
                pass
        
        return {
            'is_licensed': self.is_licensed(),
            'device_id': self._device_id,
            'trial_days_remaining': trial_info['days_remaining'],
            'license_data': license_data,
            'last_revocation_check': last_check
        }


# Global instance
_license_manager = None

def get_license_manager() -> LicenseManager:
    """Get global license manager instance"""
    global _license_manager
    if _license_manager is None:
        _license_manager = LicenseManager()
    return _license_manager
