#!/usr/bin/env python3
"""
RSA Key Pair Generator for License System
==========================================
Generates RSA-2048 key pair for signing and verifying licenses.

Usage:
    python generate_rsa_keys.py
    OR
    RSA_Key_Generator.exe

Output:
    - private_key.pem: Keep this SECRET! Used to sign licenses
    - public_key.pem: Embedded in application for license verification
"""

from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
import os
import sys
import time

def generate_rsa_keypair(key_size=2048):
    """Generate RSA key pair and save to PEM files"""

    print(f" Generating RSA-{key_size} key pair...")

    # Generate private key
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=key_size,
        backend=default_backend()
    )

    # Generate public key
    public_key = private_key.public_key()

    # Create output directory in CURRENT WORKING DIRECTORY (not script dir)
    # This fixes PyInstaller temp folder issue
    if getattr(sys, "frozen", False):
        # Running as compiled EXE - save to current directory
        base_dir = os.getcwd()
    else:
        # Running as Python script - save next to script
        base_dir = os.path.dirname(os.path.abspath(__file__))
    
    output_dir = os.path.join(base_dir, "rsa_keys")
    os.makedirs(output_dir, exist_ok=True)

    # Save private key
    private_path = os.path.join(output_dir, "private_key.pem")
    with open(private_path, "wb") as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()  # No password
        ))
    print(f" Private key saved: {private_path}")
    print("     KEEP THIS FILE SECRET! Only admin uses this!")

    # Save public key
    public_path = os.path.join(output_dir, "public_key.pem")
    with open(public_path, "wb") as f:
        f.write(public_key.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo
        ))
    print(f" Public key saved: {public_path}")
    print("    Embed this in your application")

    # Also save as Python constant for easy embedding
    python_const_path = os.path.join(output_dir, "public_key_constant.py")
    with open(public_path, "r") as f:
        public_key_pem = f.read()

    with open(python_const_path, "w") as f:
        f.write("# RSA Public Key for License Verification\n")
        f.write("# This file is auto-generated by RSA_Key_Generator\n\n")
        f.write("PUBLIC_KEY_PEM = \"\"\"\n")
        f.write(public_key_pem)
        f.write("\"\"\"\n")

    print(f" Python constant saved: {python_const_path}")
    print("\n RSA key pair generated successfully!")
    print("\n Next steps:")
    print("   1. Copy public_key_constant.py content to src/utils/license.py")
    print("   2. Keep private_key.pem safe for signing licenses")
    print("   3. Never commit private_key.pem to version control!")
    
    print("\n" + "="*50)
    print("Files created in: " + output_dir)
    print("="*50)
    
    # Wait before exit (use time.sleep for windowed mode)
    if getattr(sys, "frozen", False):
        # Running as EXE - just wait 3 seconds
        print("\nWindow will close in 3 seconds...")
        time.sleep(3)
    else:
        # Running as Python script - can use input()
        try:
            input("\nPress Enter to exit...")
        except:
            time.sleep(2)

if __name__ == "__main__":
    try:
        generate_rsa_keypair()
    except Exception as e:
        print(f"\n ERROR: {e}")
        import traceback
        traceback.print_exc()
        
        # Wait before exit
        if getattr(sys, "frozen", False):
            print("\nWindow will close in 5 seconds...")
            time.sleep(5)
        else:
            try:
                input("\nPress Enter to exit...")
            except:
                time.sleep(3)
        sys.exit(1)
