#!/usr/bin/env python3
"""
RSA Key Pair Generator for License System
==========================================
Generates RSA-2048 key pair for signing and verifying licenses.

Usage:
    python generate_rsa_keys.py

Output:
    - private_key.pem: Keep this SECRET! Used to sign licenses
    - public_key.pem: Embedded in application for license verification
"""

from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
import os

def generate_rsa_keypair(key_size=2048):
    """Generate RSA key pair and save to PEM files"""
    
    print(f"🔐 Generating RSA-{key_size} key pair...")
    
    # Generate private key
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=key_size,
        backend=default_backend()
    )
    
    # Generate public key
    public_key = private_key.public_key()
    
    # Create output directory
    output_dir = os.path.join(os.path.dirname(__file__), 'rsa_keys')
    os.makedirs(output_dir, exist_ok=True)
    
    # Save private key
    private_path = os.path.join(output_dir, 'private_key.pem')
    with open(private_path, 'wb') as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()  # No password
        ))
    print(f"✅ Private key saved: {private_path}")
    print("   ⚠️  KEEP THIS FILE SECRET! Only admin uses this!")
    
    # Save public key
    public_path = os.path.join(output_dir, 'public_key.pem')
    with open(public_path, 'wb') as f:
        f.write(public_key.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo
        ))
    print(f"✅ Public key saved: {public_path}")
    print("   📦 Embed this in your application")
    
    # Also save as Python constant for easy embedding
    python_const_path = os.path.join(output_dir, 'public_key_constant.py')
    with open(public_path, 'r') as f:
        public_key_pem = f.read()
    
    with open(python_const_path, 'w') as f:
        f.write('# RSA Public Key for License Verification\n')
        f.write('# This file is auto-generated by generate_rsa_keys.py\n\n')
        f.write('PUBLIC_KEY_PEM = """\n')
        f.write(public_key_pem)
        f.write('"""\n')
    
    print(f"✅ Python constant saved: {python_const_path}")
    print("\n🎉 RSA key pair generated successfully!")
    print("\n📋 Next steps:")
    print("   1. Copy public_key_constant.py content to src/utils/license.py")
    print("   2. Keep private_key.pem safe for signing licenses")
    print("   3. Never commit private_key.pem to version control!")

if __name__ == '__main__':
    generate_rsa_keypair()
